### ISSUE TITLE
Use with an orthographic camera?

### ISSUE THREAD

**Issue by a-type** [pmndrs/react-three-csg#12]
I've noticed that the models seem to clip if you use an orthographic camera with default settings. Seems like it's just not supported - is that true, or is there some settings / configuration to fix it?

https://codesandbox.io/s/csg-orthographic-house-c78cim?file=/src/App.js

**Comment by a-type** [comment]
Sorry, I should probably file this on three-bvh-csg.

**Comment by a-type** [comment]
Reopening as I can't seem to reproduce it there (could still be something with base r3f or the drei orthographic camera I guess?)

**Comment by isaac-mason** [comment]
The orthographic camera was inside the house model. Here's a fixed sandbox that doesn't change the `<House />` scale, but sets the `zoom` prop on `<OrthographicCamera />` instead.

https://codesandbox.io/s/csg-orthographic-house-orthographic-fixed-ki4kuf

**Comment by a-type** [comment]
Thanks for that, I feel silly... but also, orthographic cameras are weird

**Comment by isaac-mason** [comment]
No worries! They are odd to work with compared to perspective cameras, for sure. Things like this aren't visually obvious.
