### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'count')

### ISSUE THREAD

**Issue by 1uciuszzz** [pmndrs/react-three-csg#4]
```jsx
<mesh>
  <Subtraction>
    <Brush
      a
      geometry={nodes.LOD3spShape.geometry}
      material={materials["blinn3-fx"]}
    />
    <Brush b>
      <mesh position={[x, y, z]}>
        <boxGeometry args={[w, h, d]} />
        <meshStandardMaterial color={"#2a8aff"} />
      </mesh>
    </Brush>
  </Subtraction>
</mesh>
```

Duck Model URL: [https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF-Embedded/Duck.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF-Embedded/Duck.gltf)

**Comment by Will-Wrightwa** [comment]
I have this error too.

**Comment by Will-Wrightwa** [comment]
It looks like this is related to this: https://github.com/gkjohnson/three-bvh-csg/issues/94

**Comment by 1uciuszzz** [comment]
> I have this error too. 

do you resolved? i resolved this in these days, i just forgetting to compute normal and my model doesnt has uv
