### ISSUE TITLE
Accumulative Operations

### ISSUE THREAD

**Issue by dreammonkey** [pmndrs/react-three-csg#5]
Hi there, 

Thanks for this awesome addition to the pmdrs framework !

I was already using the three-bvh-csg library in one of my projects when only today I discovered this wrapper.
I tried implementing it but I soon bumped into a limitation that I can't seem to easily resolve...

The thing is that I'm parsing the Additions/Subtractions from an external file and I have lots of them.
In my (working) code I'm currently using a reducer function to do (primarily) subtractions from my base mesh.

An extract:
```javascript
return workings.reduce<Brush>((currentBrush, subtract) => {
  // do subtraction work...
  const brush2 = new Brush(subtract?.geometry.clone())
  if (subtract) {
    brush2.position.copy(subtract.position)
    brush2.rotation.copy(subtract.rotation)
  }

  brush2.updateMatrix()
  brush2.updateMatrixWorld()

  const result: Brush = csgEvaluator.evaluate(
    currentBrush,
    brush2,
    SUBTRACTION
  )
  return result
}, brush)
```

Unfortunately this setup is hard to reproduce using this library... Although I'm certain there must be a way of doing this.

I had a go at it in the sandbox below, but that approach does not work for more than 1 subtraction :/ 

```javascript
function AccumulativeSubtractions({ children, config }) {
  return config.reduce((base, c) => {
    // console.log(c, base)
    return (
      <Subtraction>
        <Brush a>{base}</Brush>
        <Brush b position={c.position} rotation={c.rotation}>
          <Cylinder config={c} />
        </Brush>
      </Subtraction>
    )
  }, children)
}
```

Do you see an easy fix for this kind of approach ? I'm happy to contribute and make a pull request, but at the moment I don't really see how this could be implemented...

The code sandbox: https://codesandbox.io/s/react-three-csg-multi-op-test-lnpuy8?file=/src/index.js

**Comment by drcmda** [comment]
i have a first test here: https://codesandbox.io/s/csg-bunny-usegroups-forked-mlgzsc?file=/src/App.js

```jsx
<mesh castShadow receiveShadow>
          <Subtraction useGroups>
            <Brush index={0} scale={1.5} position={[0, -1.04, 0]} geometry={nodes.bunny.geometry}>
              <meshNormalMaterial />
            </Brush>
            <Brush index={1} position={[-1, 1, 1]}>
              <sphereGeometry args={[0.5, 32, 32]} />
              <meshStandardMaterial color="orange" />
            </Brush>
            <Brush index={2} position={[0.5, 1, 0.9]}>
              <sphereGeometry args={[0.65, 32, 32]} />
              <meshStandardMaterial color="hotpink" />
            </Brush>
          </Subtraction>
        </mesh>
```

**Comment by drcmda** [comment]
it's done, check the main page readme
