### ISSUE TITLE
The storybook goes wrong

### ISSUE THREAD

**Issue by eric183** [pmndrs/react-three-csg#7]
Hello developer, I found the errors on the storybook sites.
like: https://csg.pmnd.rs/?path=/story/operations-addition--basic

Here is the screenshot:
![image](https://user-images.githubusercontent.com/10773980/214585903-b9ce1e63-67a3-4ab0-9eba-4f9fde71ba6e.png)

**Comment by isaac-mason** [comment]
Thanks for the issue, storybooks will be fixed with this PR: https://github.com/pmndrs/react-three-csg/pull/9

**Comment by isaac-mason** [comment]
PR has been merged, storybooks are fixed now 🙂
